# Generated by Django 4.2.6 on 2023-10-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_university_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attendees",
        ),
    ]
